---
title: "downloading lsoa boundary data"
output: html_document
---
``` {r}

nostarate <- nostarate %>% rename(LSOA11CD = lsoa11)
```

  code from [here](https://nhsrcommunity.com/blog/using-sf-to-calculate-catchment-areas/)

``` {r}
lsoa_boundaries <- read_sf(
  "https://opendata.arcgis.com/datasets/e9d10c36ebed4ff3865c4389c2c98827_0.geojson"
) %>%
  # there are other fields in the lsoa data, but we only need the LSOA11CD field
  select(LSOA11CD) %>%
  inner_join(nostarate, by = "LSOA11CD") %>%
  # this helps when combining different sf objects and get's rid of some messages
  st_set_agr(c(LSOA11CD = "identity", rate = "aggregate"))
```
https://hub.arcgis.com/datasets/ons::lower-layer-super-output-areas-december-2011-boundaries-full-clipped-bfc-ew-v3/explore?location=52.354095%2C0.123811%2C9.93


``` {r}
lsoa_boundaries <- read_sf(
  "D:/DEPED/Github/edattendances2/Lower_Layer_Super_Output_Areas__December_2011__Boundaries_Full_Clipped__BFC__EW_V3.geojson"
) %>%
  # there are other fields in the lsoa data, but we only need the LSOA11CD field
  select(LSOA11CD) %>%
  inner_join(nostarate, by = "LSOA11CD") %>%
  # this helps when combining different sf objects and get's rid of some messages
  st_set_agr(c(LSOA11CD = "identity", rate = "aggregate"))
```


https://opendatacommunities.org/resource.json?uri=http%3A%2F%2Fopendatacommunities.org%2Fid%2Fgeography%2Fadministration%2Frgn%2FE12000003

``` {r}
ggplot() +
  # first plot the lsoa boundaries and colour by the population
  geom_sf(data = lsoa_boundaries, aes(fill = rate), colour = NA) +
    scale_fill_distiller(type = "div", palette = "Spectral",
                       # tidy up labels in the legend, display as thousands
                       ) +
  theme_void() +
  theme(legend.position = c(0, 0.98),
        legend.justification = c(0, 1)) +
  labs(fill = "Annual ED attendance rate per thousand population")
```

``` {r}
m <- leaflet () %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolygons( data = lsoa_boundaries,
        stroke = TRUE,
        weight = 0.5,
        color = "#37B1ED",
        opacity = 1,
        fillColor = "#37B1ED",
        fillOpacity = 0.5)

m
```




``` {r}
LSOABins <- c(0, 50, 100, 200, 250, 350, 800)
LSOAPal <- colorBin ("YlGnBu", domain = lsoa_boundaries$rate, bins = LSOABins)
```



``` {r}
m <-leaflet() %>%
addProviderTiles(providers$CartoDB.Positron) %>%
  addPolygons( data = lsoa_boundaries,
stroke = TRUE,
weight = 0.2,
color="#ABABAB",
smoothFactor = 0.3,
opacity = 0.9,
fillOpacity= 0.8,
fillColor = ~LSOAPal (rate))

m
```

``` {r}
LSOAPal <- colorNumeric(
  palette = "YlGnBu",
  domain = lsoa_boundaries$rate)

```

``` {r}
m <-leaflet() %>%
addProviderTiles(providers$CartoDB.Positron) %>%
  addPolygons( data = lsoa_boundaries,
stroke = TRUE,
weight = 0.2,
color="#ABABAB",
smoothFactor = 0.3,
opacity = 0.9,
fillOpacity= 0.8,
fillColor = ~LSOAPal(rate)) %>%
addLegend("bottomright",opacity = 1,
          colors =c("#ffffcc","#c7e9b4","#7fcdbb","#41b6c4","#1d91c0","#225ea8","#0c2c84"),
          title = "Annual ED attendance rates/1000 population",
          labels= c("On the floor","Pretty low","Slightly low","About average","Slightly high", "Pretty high", "Through the roof")
          )

m
```

This is great, we now need to make a couple of functions to do the
following...

1) Subset the data by any grouping we choose, gender, age boundary etc.
2) A function to plot this.

``` {r, label='subsetting_function'}
subset_data <- function(data, min_age, max_age, gender = NULL, ...) {
  data <- data |> dplyr::filter(age > min_age &
                                age < max_age)

  if gender != NULL {
    data <- data |> dplyr::filter(gender = gender)

  }

  return data
}
```

``` {r, label='leaflet_function'}
leaflet_plot <- function(data, weight=0.5, opacity=1, fillOpacity=0.5,
                         color="#37B1ED",
                         fillColor= colorNumeric(palette = "YlGnBu",
                                                 domain = lsoa_boundaries$rate),
                         smoothFactor=0.3,
                         LSOABins=c(0, 50, 100, 200, 250, 350, 800)
                         LSOAPal=colorBin("YlGnBu",
                                          domain=lsoa_boundaries$rate,
                                          bins = LSOABins),
                         legendPosition="bottomright",
                         legendOpacity=1,
                         legendColors=c("#ffffcc",
                                        "#c7e9b4",
                                        "#7fcdbb",
                                        "#41b6c4",
                                        "#1d91c0",
                                        "#225ea8",
                                        "#0c2c84"),
                         legendTitle="Annual ED attendance rates/1000 population",
                         legendLabels=c("On the floor",
                                        "Pretty low",
                                        "Slightly low",
                                        "About average",
                                        "Slightly high",
                                        "Pretty high",
                                        "Through the roof")
                         ) {
m <- leaflet() |>
     addProviderTiles(providers$CartoDB.Positron) |>
     addPolygons(data = lsoa_boundaries,
                 stroke = TRUE,
                 weight = weight,
                 color = color,
                 smoothFactor = smoothFactor,
                 opacity = opacity,
                 fillColor = fillColor,
                 fillOpacity = fillOpacity) |>

                 addLegend(legendPosition,
                           legendOpacity,
                           colors=legendColors,
                           title=legendTitle,
                           labels=legendLabels)
}
```
