---
title: "mapweightedrate"
output: html_document
---
``` {r}

anasamp <- anasamp %>% rename(LSOA11CD = lsoa11)
```
  
  code from [here](https://nhsrcommunity.com/blog/using-sf-to-calculate-catchment-areas/)

``` {r}
lsoa_boundaries <- read_sf(
  "https://opendata.arcgis.com/datasets/e9d10c36ebed4ff3865c4389c2c98827_0.geojson"
) %>%
  # there are other fields in the lsoa data, but we only need the LSOA11CD field
  select(LSOA11CD) %>%
  inner_join(anasamp, by = "LSOA11CD") %>%
  # this helps when combining different sf objects and get's rid of some messages
  st_set_agr(c(LSOA11CD = "identity", rate = "aggregate"))
```
https://hub.arcgis.com/datasets/ons::lower-layer-super-output-areas-december-2011-boundaries-full-clipped-bfc-ew-v3/explore?location=52.354095%2C0.123811%2C9.93


``` {r}
lsoa_boundaries <- read_sf(
  "D:/DEPED/Github/edattendances2/Lower_Layer_Super_Output_Areas__December_2011__Boundaries_Full_Clipped__BFC__EW_V3.geojson"
) %>%
  # there are other fields in the lsoa data, but we only need the LSOA11CD field
 ## removing this line to see if I can add labels select(LSOA11CD) %>%
  inner_join(anasamp, by = "LSOA11CD") %>%
  # this helps when combining different sf objects and get's rid of some messages
  st_set_agr(c(LSOA11CD = "identity", rate = "aggregate"))
```


https://opendatacommunities.org/resource.json?uri=http%3A%2F%2Fopendatacommunities.org%2Fid%2Fgeography%2Fadministration%2Frgn%2FE12000003

``` {r}
ggplot() +
  # first plot the lsoa boundaries and colour by the population
  geom_sf(data = lsoa_boundaries, aes(fill = werate), colour = NA) +
    scale_fill_distiller(type = "div", palette = "Spectral",
                       # tidy up labels in the legend, display as thousands
                       ) +
  theme_void() +
  theme(legend.position = c(0, 0.98),
        legend.justification = c(0, 1)) +
  labs(fill = "Annual ED attendance rate per thousand population")
```

``` {r}
m <- leaflet () %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolygons( data = lsoa_boundaries,
        stroke = TRUE,
        weight = 0.5,
        color = "#37B1ED",
        opacity = 1,
        fillColor = "#37B1ED",
        fillOpacity = 0.5)

m
```




``` {r}
LSOABins <- c(0, 500, 1500, 2000, 2500, 3000, 4000)
LSOAPal <- colorBin ("YlGnBu", domain = lsoa_boundaries$werate, bins = LSOABins)
```




``` {r}
LSOAPal <- colorNumeric(
  palette = "YlGnBu",
  domain = lsoa_boundaries$werate)

```


```{r}
lsoa_boundaries$popup <- paste("<strong>",lsoa_boundaries$LSOA11NM,"</strong>", "</br>", 
                    lsoa_boundaries$LSOA11CD, "</br>",
                      "Annual ED attendance rate/1000", prettyNum(lsoa_boundaries$werate, big.mark = ","))
```

``` {r}
m <-leaflet() %>%
addProviderTiles(providers$CartoDB.Positron) %>%
  addPolygons( data = lsoa_boundaries,
stroke = TRUE,
weight = 0.2,
color="#ABABAB",
smoothFactor = 0.3,
opacity = 0.9,
fillOpacity= 0.8,
popup = ~popup,
highlightOptions = highlightOptions(color = "#E2068A", weight = 1.5,
                                                  bringToFront = TRUE, fillOpacity = 0.5),
fillColor = ~LSOAPal (werate)) %>% 
addLegend("bottomright",opacity = 1,
          colors =c("#ffffcc","#c7e9b4","#7fcdbb","#41b6c4","#1d91c0","#225ea8","#0c2c84"),
          title = "Annual ED attendance rates/1000 population",
          labels= c("On the floor","Pretty low","Slightly low","About average","Slightly high", "Pretty high", "Through the roof")
          )

m
```
